# Generated by Django 5.0.2 on 2024-02-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payclick', '0002_item_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_id',
        ),
    ]
