# Generated by Django 5.0.2 on 2024-02-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payclick', '0004_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
