# Generated by Django 5.0.2 on 2024-03-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payclick', '0007_remove_discount_order_remove_tax_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
