# Generated by Django 5.0.2 on 2024-03-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payclick', '0008_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
