# Generated by Django 5.0.2 on 2024-03-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payclick', '0009_remove_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='payclick.item', verbose_name='Товары в заказе'),
        ),
    ]
