# Generated by Django 5.0.2 on 2024-03-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payclick', '0010_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа в Stripe'),
        ),
    ]
